Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,7 +7,7 @@ on:
 
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-22.04
 
     steps:
     - name: Checkout repository
@@ -18,12 +18,15 @@ jobs:
       with:
         python-version: '3.10'
 
-    - name: Install dependencies
+    - name: Install System Dependencies
       run: |
         sudo apt-get update
-        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libffi-dev libssl-dev
-        pip install --upgrade pip
-        pip install buildozer cython==0.29.33
+        sudo apt-get install -y \
+          git zip unzip openjdk-17-jdk python3-pip autoconf libtool \
+          pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libffi-dev \
+          libssl-dev libltdl-dev ccache clang ffmpeg
+        pip install --upgrade pip setuptools wheel
+        pip install "cython<3.0.0" buildozer
 
     - name: Build APK with Buildozer
       run: |
@@ -32,7 +35,7 @@ jobs:
         elif [ -f "garage_app/buildozer.spec" ]; then
           cd garage_app && buildozer -v android debug
         else
-          echo "Помилка: файл buildozer.spec не знайдено!" && exit 1
+          echo "Error: buildozer.spec not found!" && exit 1
         fi
 
     - name: Upload APK Artifact
